### ISSUE TITLE
Sharing failed

### ISSUE THREAD

**Issue by milesscherrer** [Lg0gs/react-native-tiktok#1]
Trying to share a video to TikTok on iOS but only get SHARING_FAILED. Followed the instructions for AppDelegate.m and info.plist and got a TikTok AppID.

Do I need to add something more to AppDelegate.m to make sharing work? Or do I need to authenticate first?

What are the general steps to make share work?

Thanks!

**Comment by Lg0gs** [comment]
Hi @milesscherrer 
Did you insert your iOS bundle id correctly?

**Comment by milesscherrer** [comment]
Using RNFetchBlob.fs.dirs.DocumentDir + `/${filename.mp4}` and also tried appending 'file://' before.

Same video works with Instagram Stories sharing (singleShare with react-native-share) from same path.

**Comment by Lg0gs** [comment]
@milesscherrer 
Do your bundle IDs match?

**Comment by milesscherrer** [comment]
Yes I specified only bundle ID on the TikTok for Developers form and it is approved. Not App ID = team ID + bundle ID but only bundle ID. Is this correct?

**Comment by Lg0gs** [comment]
![image](https://user-images.githubusercontent.com/47741923/130779659-42fe89fd-3c9a-48bd-97e7-adf082edc9ff.png)
![image](https://user-images.githubusercontent.com/47741923/130779717-d055a72e-0ebc-4afe-9c18-76737f3ed8fb.png)
These IDs must be the same, otherwise id won't work

**Comment by milesscherrer** [comment]
Yes they are identical

**Comment by Lg0gs** [comment]
Can you use another library to pick a video from the gallery just to be sure that it's a file path issue?
[react-native-image-picker](https://github.com/react-native-image-picker/react-native-image-picker) for example.

**Comment by milesscherrer** [comment]
Yes same (SHARING_FAILED) with picker and choosing a camera roll vertical video.

In example.js there is an init() but that should only be needed for android right?

**Comment by Lg0gs** [comment]
Yes, this isn't for iOS

**Comment by milesscherrer** [comment]
Got it working - the problem was that I added the TikTok info.plist data in the existing attributes instead of adding all lines just below final </dict> element. Thanks for the support!

**Comment by Lg0gs** [comment]
@milesscherrer 
Ok. Get me feedback, please, regarding Android.

**Comment by vforvasile** [comment]
@Lg0gs Auth side works on Android, the Sharing fails with **Insufficient permissions** error. 

I'm not quite sure what **Android App Signature** input field needs in order to make Sharing work in Dev Portal. Our app opens TikTok with the right path and then closes TikTok instantly with error 20003. Although we added all the permissions.

Any thoughts?

**Comment by Lg0gs** [comment]
@vforvasile Sorry, I checked your question just now, did you solve it?

**Comment by vforvasile** [comment]
nope

**Comment by Lg0gs** [comment]
@vforvasile Did you check iOS part also?
