### ISSUE TITLE
Not getting the callback code on iOS and only sometimes on Android

### ISSUE THREAD

**Issue by KristineTrona** [Lg0gs/react-native-tiktok#13]
Hello, 

First of all, thank you for this great library! 
I've run into an issue, where I don't seem to be getting the callback after a successful share to TikTok on iOS.

The code:
```
share(url, (code: string) => {
  console.log("Came back from TikTok share", code);
});
```

The sharing itself works perfectly, but I never get the callback log.

On Android I've implemented the additional logic with event listener and get the callback logs:
-  when the user shared successfully and tapped on "Back to MyApp"
-  when there was an error with sharing

but not when:
- the user shared successfully and tapped on "Stay in TikTok"
- user canceled sharing in the share preview and navigated back to the app

### Questions:
**1. What could I be missing on iOS?**
**2. Is the behaviour that I am getting on Android correct and is it the expected behaviour on both Platforms?**

Any help is much appreciated. Thank you!

**Comment by Lg0gs** [comment]
Hi @KristineTrona and thank you
Did you return from the Tiktok to your App (iOS case)?

**Comment by KristineTrona** [comment]
Hey @Lg0gs yes, I got the prompt to either return to the app or stay in TikTok. Choosing "Back to MyApp" did not give me the callback. 

I did have to downgrade the `TikTokOpenSDK` to `5.0.0` in order to fix [this build issue](https://github.com/Lg0gs/react-native-tiktok/issues/7) - could that have anything to do with it?

**Comment by KristineTrona** [comment]
I just noticed a warning saying:

`URL with scheme called while no listener was set {"url": "$TikTokClientKey://response.bridge.bytedance.com/share?from_platform=tiktoksharesdk*request_id=....."}`

**Comment by Lg0gs** [comment]
@KristineTrona 
Did you go through these steps?
<img width="883" alt="image" src="https://user-images.githubusercontent.com/47741923/193763476-a03b1f1c-abb2-46a1-b140-5e41f4e766df.png">

**Comment by KristineTrona** [comment]
Yes, I had this added just before my final `</dict>` element, however, I noticed that this may not be working, because I already have `LSApplicationQueriesSchemes` and `CFBundleURLTypes` keys present earlier in the `Info.plist` file.

So I've tried to rearrange it as:

```
<plist version="1.0">
<dict>

   <!-- Other content -->

    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>(other string)</string>
            </array>
        </dict>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
              <string>$TikTokClientKey</string>
            </array>
        </dict>
    </array>

    <!-- Other content -->

    <key>LSApplicationQueriesSchemes</key>
    <array>

        <!-- Other strings -->

        <string>tiktokopensdk</string>
        <string>tiktoksharesdk</string>
        <string>snssdk1180</string>
        <string>snssdk1233</string>
    </array>

    <!-- Other content -->

    <key>TikTokAppID</key>
    <string>$TikTokClientKey</string>
</dict>
</plist>

```

But I still get the same warning.

**Comment by Lg0gs** [comment]
@KristineTrona 
Did you change this `<string>$TikTokClientKey</string>` line with your real client key?

**Comment by KristineTrona** [comment]
Yes, in both places and it is the correct key, because using the same key for Android does work.

**Comment by Lg0gs** [comment]
@KristineTrona 
```
<key>CFBundleURLTypes</key>
<array>
    <dict>
	<key>CFBundleURLSchemes</key>
	<array>
	    <string>fb_key</string>
	    <string>tiktok_client_key</string>
	</array>
    </dict>
</array>
```

this is my URL types, you have 2 dicts instead, can you try my way?

**Comment by KristineTrona** [comment]
@Lg0gs after a lot of searching we finally found that the problem is not in any way with your library, but with our own internal setup. The problem was that we initialized `TikTokOpenSDKApplicationDelegate` after inititializing `RCTLinkingManager`, so the callback link was handled as a deep link instead. 

Thank you a lot for your help, I will close this issue now :)

**Comment by Lg0gs** [comment]
@KristineTrona Wish you all the best

**Comment by lucianobracco-geojam** [comment]
Wht about android?
