### ISSUE TITLE
NETWORK_ERROR on sharing

### ISSUE THREAD

**Issue by gbermudez1992** [Lg0gs/react-native-tiktok#2]
share callback always returns NETWORK_ERROR on iOS. Haven't test it on Android yet.

**Comment by Lg0gs** [comment]
@gbermudez1992 Hi
Are you using mobile data or wifi?

**Comment by GeoffAbbott** [comment]
@Lg0gs also getting NETWORK_ERROR on every share attempt. IOS both wifi and cell data. Specific error codes are -1, 2002 Invalid Params

**Comment by Lg0gs** [comment]
@GeoffAbbott
Strange, I created a new RN app and auth and sharing work.
Did you follow [those](https://developers.tiktok.com/doc/getting-started-ios-quickstart-objective-c) steps and modified AppDelegate.m and Info.plist correctly?
